services:
  - type: web
    name: esp32-cam-streaming
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: esp32-cam-streaming
          property: port
      - key: ADDRESS
        fromService:
          type: web
          name: esp32-cam-streaming
          property: host
      - key: JWT_SECRET
        generateValue: true
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
    branch: main
